package:
  name: ffevaluation
  version: {{ environ.get('BUILD_VERSION', 0 ) }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}

  script_env:
   - OSNAME

requirements:
  build:
    - python 
    - requests
    
  run:
    - python 
DEPENDENCY_PLACEHOLDER

about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
