name: Test code

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    defaults: # Needed for conda
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: acellera,conda-forge,defaults

      - name: Install pip dependencies
        run: |
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Insert placeholder values
        run: |
          pip install toml pyyaml setuptools-scm
          python package/ffevaluation/insert_placeholder_values.py

      - name: Build and install conda package
        run: |
          mamba install rattler-build -c conda-forge
          rattler-build package/ffevaluation --output-dir /tmp/pkg/ --no-include-recipe -c acellera -c conda-forge
          mamba install /tmp/pkg/noarch/ffevaluation-*.conda -y -q -c acellera -c conda-forge

      - name: Run tests and coverage
        run: |
          mamba install openmm
          pytest ./tests/

      - name: Upload to anaconda
        if: startsWith(github.ref, 'refs/tags')
        run: |
          mamba install anaconda-client
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload /tmp/pkg/noarch/ffevaluation-*.conda -u acellera
